### ISSUE TITLE
Conversion failed!

### ISSUE THREAD

**Issue by Sisi497** [C0D3D3V/bbb-dl-fork#3]
It downloads all the files but it fails at the end 
Traceback (most recent call last):
  File "/home/sisi/.local/bin/bbb-dl", line 8, in <module>
    sys.exit(main())
  File "/home/sisi/.local/lib/python3.8/site-packages/bbb_dl/main.py", line 498, in main
    BBBDL(args.verbose).run(args.URL, args.add_webcam, args.keep_tmp_files)
  File "/home/sisi/.local/lib/python3.8/site-packages/bbb_dl/main.py", line 190, in run
    slideshow_w, slideshow_h = self._rescale_slides(slides_infos)
  File "/home/sisi/.local/lib/python3.8/site-packages/bbb_dl/main.py", line 387, in _rescale_slides
    self.ffmpeg.rescale_image(slide.path, rescaled_path, new_width, new_height)
  File "/home/sisi/.local/lib/python3.8/site-packages/bbb_dl/ffmpeg.py", line 71, in rescale_image
    self.pp.run_ffmpeg(image, out_file, ["-vf", "pad=%s:%s:ow/2-iw/2:oh/2-ih/2" % (width, height)])
  File "/home/sisi/.local/lib/python3.8/site-packages/bbb_dl/ffmpeg.py", line 62, in run_ffmpeg
    self.run_ffmpeg_multiple_files([path], out_path, opts, opts_before)
  File "/home/sisi/.local/lib/python3.8/site-packages/bbb_dl/ffmpeg.py", line 58, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!

**Comment by ferk6a** [comment]
This is due to
https://github.com/C0D3D3V/bbb-dl/blob/089136dbf595772a769b7e83219f394b8d140b95/bbb_dl/ffmpeg.py#L70
(height and width are in the wrong order).

It has since been fixed: https://github.com/C0D3D3V/bbb-dl/commit/7884f7d7475e068c74079d2c642908bc436a99b3#diff-dc441e83f3326b9ea21048985c07962bc45f5d497d774a06da8962644b185276R70.

But the author hasn't pushed a new version to PyPy just yet.

**Comment by yilinwumath** [comment]
Hello! This error "Conversion failed!" still appears. When will the new version be released on PyPy? Thank you very much!

**Comment by C0D3D3V** [comment]
Lol, I'm very sorry. I'm somehow did not got notified about this issue, maybe because this is only a fork. I will create the new pypi package today.

**Comment by C0D3D3V** [comment]
It is now released. I apologize for this delay.

You can update your version with `pip install -U bbb-dl`
